fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    download_file: git://github.com/opentable/puppet-download_file.git
    powershell: git://github.com/joshcooper/puppetlabs-powershell.git
  symlinks:
    iis_rewrite: "#{source_dir}"
